// Run: NODE_PATH=/path/to/node_modules node tests/frontend_security.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { JSDOM } = require('jsdom');
const dom = new JSDOM(fs.readFileSync('frontend/index.html', 'utf8'), {
    url: 'https://courtlog.test/', runScripts: 'outside-only', pretendToBeVisual: true
});
const ctx = dom.getInternalVMContext();
new vm.Script(fs.readFileSync('frontend/app.js', 'utf8')).runInContext(ctx);
const run = code => new vm.Script(code).runInContext(ctx);
const attack = `x');window.stolen=true;//<img src=x onerror=alert(1)>`;
const record = {case_id: attack, case_type: attack, court: attack, scan_events: [],
    adjournment_count: 0, days_since_filing: 1, delay_risk_score: 0.1, judgment_status: 'Pending'};
run(`renderHeatmapTable([${JSON.stringify(record)}])`);
const table = dom.window.document.getElementById('cases-table-body');
assert.equal(table.querySelector('img'), null);
const scan = table.querySelector('[data-case-action="scan"]');
assert.equal(scan.getAttribute('onclick'), null);
assert.equal(scan.dataset.recordId, attack);
assert.equal(dom.window.document.getElementById('scan-staff-id'), null, 'scan actor is not a user-entered staff ID');
run(`casesData = [${JSON.stringify({...record, case_id:attack, dcr_approval_required:true, dcr_acknowledged_at:'2026-10-01T12:00:00Z', dcr_acknowledged_by:attack})}]; renderDCRTable()`);
const dcrTable = dom.window.document.getElementById('dcr-approval-table-body');
assert.equal(dcrTable.querySelector('img, svg'), null, 'DCR acknowledgement metadata is rendered safely');
const acknowledge = dcrTable.querySelector('[data-case-action="acknowledgeDCR"]');
assert.ok(acknowledge);
assert.equal(acknowledge.getAttribute('onclick'), null);
run('acknowledgeDCRReview = id => { window.acknowledgedId = id; }');
acknowledge.dispatchEvent(new dom.window.MouseEvent('click', {bubbles:true}));
assert.equal(dom.window.acknowledgedId, attack);
run(`aiRiskData = [{case_id:'SAFE/AI', case_type:'Fictional civil', court:'Fictional Court', adjournment_count:4, days_since_filing:90, delay_risk_score:0.8, judgment_status:'Pending'}]; alert = message => { window.explanationMessage = message; }; showExplainability('SAFE/AI')`);
assert.match(dom.window.explanationMessage, /synthetic and rule-generated/);
assert.match(dom.window.explanationMessage, /not a legal finding/);
assert.doesNotMatch(dom.window.explanationMessage, /statutory limit|Nigerian court records/);
assert.ok(dom.window.document.querySelector('link[rel="manifest"]'), 'the installable PWA manifest is linked');
assert.match(dom.window.document.querySelector('#tab-ai-risk').textContent, /generated synthetic training scenarios/);
assert.match(dom.window.document.querySelector('#tab-ai-risk').textContent, /not legal findings/);
assert.doesNotMatch(dom.window.document.querySelector('#tab-ai-risk').textContent, /3,000\+ Nigerian Court Records/);
assert.ok(dom.window.document.getElementById('qr-label-canvas'), 'QR labels are rendered locally on a canvas');
assert.equal(dom.window.document.querySelector('#qr-display-img img'), null, 'no remote QR image is embedded');
assert.match(fs.readFileSync('frontend/c2-pwa.js', 'utf8'), /QRCode\.toCanvas/, 'QR generation uses the local qrcode package');
const historyAttack = `x');window.stolen=true;//<img src=x onerror=alert(1)>`;
run(`casesData = [${JSON.stringify({...record, case_id:'SAFE/MISSING', file_missing_history:[{action:'found', actor_user_id:historyAttack, timestamp:'2026-10-01T00:00:00Z', found_location:historyAttack, reason:historyAttack}]})}]; const historySelect = document.getElementById('missing-history-case-id'); historySelect.replaceChildren(new Option('Fictional case', 'SAFE/MISSING')); historySelect.value = 'SAFE/MISSING'; renderFileMissingHistory();`);
assert.equal(dom.window.document.querySelector('#missing-file-history img'), null, 'missing/found history uses safe text rendering');
assert.ok(dom.window.document.querySelector('#missing-file-history').textContent.includes(historyAttack));
run('shortcutQRScan = id => { window.selectedId = id; }');
scan.dispatchEvent(new dom.window.MouseEvent('click', {bubbles: true}));
assert.equal(dom.window.selectedId, attack);
const custody = table.querySelector('[data-case-action="assignSheriff"]');
assert.ok(custody);
assert.equal(custody.getAttribute('onclick'), null);
run('openAssignSheriffModal = id => { window.custodyCaseId = id; }');
custody.dispatchEvent(new dom.window.MouseEvent('click', {bubbles: true}));
assert.equal(dom.window.custodyCaseId, attack);
run(`renderHeatmapTable([${JSON.stringify({...record, case_id:'SAFE/COMBINED', file_missing:true, file_missing_report:{resolved:false}, custody_alert:true})}])`);
assert.match(table.textContent, /File Missing/);
assert.match(table.textContent, /Registry Idle/, 'idle-custody alert remains visible beside missing status');
assert.equal(dom.window.stolen, undefined);
run(`casesData = [${JSON.stringify({...record, case_id:'SAFE/EXECUTION', judgment_status:'Delivered', enforcement_non_compliant:true})}]; renderExecutionTable()`);
assert.match(dom.window.document.querySelector('#judgments-table-body').textContent, /Review Prompt \(90d\+\)/);
assert.doesNotMatch(dom.window.document.querySelector('#judgments-table-body').textContent, /Compliant|Overdue/);
assert.match(dom.window.document.querySelector('#tab-execution').textContent, /not a legal non-compliance finding/);
run(`whatsappLogs = [{created_at: new Date().toISOString(), recipient_masked: ${JSON.stringify(attack)}, status: ${JSON.stringify(attack)}, case_id: ${JSON.stringify(attack)}, template_name: ${JSON.stringify(attack)}, error_message: ${JSON.stringify(attack)}}]; renderWhatsAppLogs()`);
assert.equal(dom.window.document.querySelector('#whatsapp-logs-container img'), null, 'WhatsApp delivery logs render provider fields as escaped text');
assert.ok(dom.window.document.querySelector('#whatsapp-logs-container').textContent.includes(attack));
run(`showToast(${JSON.stringify(attack)})`);
assert.equal(dom.window.document.querySelector('#toast-container img'), null);
run(`casesData = [${JSON.stringify({...record, case_id:'SAFE/1', case_title:attack})}]; showWritModal('SAFE/1','Garnishee Order',${JSON.stringify(attack)},${JSON.stringify(attack)})`);
assert.equal(dom.window.document.querySelector('#modal-writ-content img'), null);
console.log('Frontend security: rendering boundaries, QR privacy, and delegated custody actions passed');
dom.window.close();
